export const ADD_CARD_TO_CONSTRUCTOR = "ADD_CARD_TO_CONSTRUCTOR";
export const DELETE_CARD_FROM_CONSTRUCTOR = "DELETE_CARD_FROM_CONSTRUCTOR";
export const CHANGE_INGREDIENT_POSITION = "CHANGE_INGREDIENT_POSITION";